// src/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'es';

export const translations: Record<Language, Record<string, string>> = {
  "en": {
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.done": "Done",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.close": "Close",
    "common.reset": "Reset",
    "common.apply": "Apply",
    "common.search": "Search",
    "common.viewAll": "View All",
    "common.step": "Step",
    "common.of": "of",
    "common.today": "Today",
    "common.all": "All",
    "common.tops": "Tops",
    "common.outerwear": "Outerwear",
    "common.pants": "Pants",
    "common.shoes": "Shoes",
    "common.accessories": "Accessories",
    "app.navTitle": "FitGlass Flow Navigator",
    "app.navSubtitle": "Jump directly to any of the 16 native screens",
    "app.allScreens": "All Screens (16)",
    "header.brand": "FitGlass",
    "header.subtitle": "Digital Wardrobe Atelier",
    "tabs.home": "Home",
    "tabs.wardrobe": "Wardrobe",
    "tabs.fittingRoom": "Fitting Room",
    "tabs.colorStudio": "Color Studio",
    "tabs.profile": "Profile",
    "welcome.brandBadge": "ATELIER · AUTUMN / WINTER 2026",
    "welcome.wordmark": "FITGLASS",
    "welcome.tagline": "Virtual wardrobe & intelligent 3D fitting room.",
    "welcome.calibration": "BODY RATIO · 1:1.618 OPTICAL MATRIX",
    "welcome.feature1Title": "Digital Profile",
    "welcome.feature1Desc": "Precise millimeter body simulation",
    "welcome.feature2Title": "Drape & Fit",
    "welcome.feature2Desc": "Shape key & tension prediction",
    "welcome.feature3Title": "Color Studio",
    "welcome.feature3Desc": "Harmonized palette resonance",
    "welcome.getStarted": "Get Started",
    "welcome.haveAccount": "I already have an account",
    "bodyProfile.stepBadge": "STEP 01 OF 02",
    "bodyProfile.title": "Create your fit profile",
    "bodyProfile.subtitle": "Your measurements help FitGlass simulate garment fit.",
    "bodyProfile.metric": "Metric (cm)",
    "bodyProfile.imperial": "Imperial (in)",
    "bodyProfile.calibrationBadge": "PARAMETRIC CALIBRATION",
    "bodyProfile.calibrationDesc": "Millimeter avatar generated locally from biomechanical proportions.",
    "bodyProfile.height": "Height",
    "bodyProfile.weight": "Weight",
    "bodyProfile.chest": "Chest Circumference",
    "bodyProfile.waist": "Waistline Circumference",
    "bodyProfile.hips": "Hip Breadth",
    "bodyProfile.shoulders": "Shoulder Span",
    "bodyProfile.saveProfile": "Save Profile & Continue",
    "bodyProfile.skip": "Skip for now (use standard mannequin)",
    "home.heroPreheader": "AUTUMN / WINTER 2026",
    "home.heroTitle": "Your wardrobe, perfectly fitted.",
    "home.heroSubtitle": "Simulate exact garment drape, tension, and color harmony on your digital silhouette.",
    "home.fittingRoom": "Fitting Room",
    "home.addClothing": "Add Clothing",
    "home.quickAddGarment": "Add Garment",
    "home.quickFittingRoom": "Fitting Room",
    "home.quickColorStudio": "Color Studio",
    "home.quickAllClothes": "All Clothes",
    "home.recentLooks": "Recent Looks",
    "home.recentLooksSubtitle": "Composed outfits & fit balance",
    "home.buildOutfit": "Build Outfit",
    "home.garmentsCount": "garments",
    "home.yourWardrobe": "Your Wardrobe",
    "home.recentGarments": "Recently analyzed garments",
    "home.colorPalette": "Color Palette",
    "home.skinUndertone": "Skin undertone resonance",
    "home.studio": "Studio",
    "home.neutralHarmonies": "Curated Neutral & Deep Harmonies",
    "wardrobe.title": "Wardrobe",
    "wardrobe.curatedPieces": "curated pieces",
    "wardrobe.searchPlaceholder": "Search piece, color, brand...",
    "wardrobe.filterTitle": "Filter Wardrobe",
    "wardrobe.filterSubtitle": "Refine by fit cut or palette harmony",
    "wardrobe.filterFit": "Fit Silhouette",
    "wardrobe.filterPalette": "Palette Harmony Only",
    "wardrobe.filterPaletteDesc": "Show only items matching skin resonance",
    "wardrobe.reset": "Reset",
    "wardrobe.apply": "Apply Filters",
    "wardrobe.emptyTitle": "No garments found",
    "wardrobe.emptyDesc": "Try changing your search term or active filters.",
    "addGarment.title": "Add a garment",
    "addGarment.confirmCapture": "Confirm capture",
    "addGarment.cameraFrame": "Camera frame",
    "addGarment.detected": "GARMENT DETECTED",
    "addGarment.hint": "Place the garment on a clean surface for better results.",
    "addGarment.retake": "Retake Photo",
    "addGarment.analyze": "Analyze Garment",
    "addGarment.tapShutter": "Tap shutter to capture garment boundary",
    "garmentProcessing.badge": "PIPELINE · COMPUTER VISION",
    "garmentProcessing.title": "Analyzing garment",
    "garmentProcessing.subtitle": "Extracting spatial boundaries, fabric attributes, and color palette.",
    "garmentProcessing.step1": "Removing background",
    "garmentProcessing.step1Desc": "Edge matte segmentation",
    "garmentProcessing.step2": "Identifying garment",
    "garmentProcessing.step2Desc": "Category & weave detection",
    "garmentProcessing.step3": "Extracting colors",
    "garmentProcessing.step3Desc": "Hex clustering & harmony tags",
    "garmentProcessing.step4": "Preparing fit data",
    "garmentProcessing.step4Desc": "Shape key morph bounds",
    "garmentProcessing.complete": "ANALYSIS COMPLETE",
    "garmentProcessing.viewExtracted": "View Extracted Attributes",
    "garmentDetails.title": "Garment Attributes",
    "garmentDetails.subtitle": "Extracted by Vision Engine",
    "garmentDetails.matteTag": "BACKGROUND REMOVED · CLEAN MATTE",
    "garmentDetails.nameLabel": "GARMENT NAME",
    "garmentDetails.categoryLabel": "CATEGORY",
    "garmentDetails.brandLabel": "BRAND / ATELIER",
    "garmentDetails.materialLabel": "FABRIC & COMPOSITION",
    "garmentDetails.colorLabel": "EXTRACTED COLOR PALETTE",
    "garmentDetails.sizeLabel": "SIZE SPECIFICATION",
    "garmentDetails.fitLabel": "INTENDED FIT CUT",
    "garmentDetails.notesLabel": "EDITORIAL STYLING NOTES",
    "garmentDetails.save": "Save to Wardrobe",
    "garmentDetails.cancel": "Cancel",
    "garmentView.sizeBadge": "SIZE",
    "garmentView.paletteHarmony": "PALETTE HARMONY",
    "garmentView.added": "ADDED",
    "garmentView.tryOn": "Try On in 3D",
    "garmentView.editAttributes": "Edit Garment Attributes",
    "garmentView.fabricDetails": "FABRIC & SPECIFICATIONS",
    "garmentView.material": "Material",
    "garmentView.fitCut": "Fit Cut",
    "garmentView.colorCode": "Color Hex",
    "garmentView.editorialNotes": "EDITORIAL NOTES",
    "fittingRoom.badge": "FITTING ROOM",
    "fittingRoom.studioTitle": "Digital Drape Studio",
    "fittingRoom.fitTag": "FIT",
    "fittingRoom.adjustFit": "Adjust Fit & Tension",
    "fittingRoom.switchGarment": "Switch Piece",
    "fittingRoom.seeResult": "See Fit Result",
    "fittingRoom.buildOutfit": "Build Outfit",
    "fittingRoom.sheetTitle": "Parametric Fit Calibration",
    "fittingRoom.sheetSubtitle": "Fine-tune tension and drape across key anatomical points",
    "fittingRoom.targetSize": "TARGET SIZE",
    "fittingRoom.tensionEased": "Eased / Relaxed",
    "fittingRoom.tensionSnug": "Snug / Tailored",
    "fittingRoom.tensionLabel": "Overall Fit Tension",
    "fittingRoom.chestLabel": "Chest Width",
    "fittingRoom.waistLabel": "Waist Span",
    "fittingRoom.hipsLabel": "Hip Circumference",
    "fittingRoom.shouldersLabel": "Shoulder Breadth",
    "fittingRoom.applyFit": "Apply Fit Calibration",
    "fittingRoom.switchSheetTitle": "Select Garment to Try On",
    "fittingRoom.switchSheetSubtitle": "Choose from your digital wardrobe pieces",
    "fitResult.title": "Fit Analysis",
    "fitResult.scoreBadge": "EVALUATION SCORE",
    "fitResult.scoreValue": "Optimal Equilibrium",
    "fitResult.scorePercent": "98.4% HARMONY",
    "fitResult.scoreDesc": "Drape tension across lateral torso is balanced. No excessive pulling or fabric bunching detected.",
    "fitResult.regionHeader": "ANATOMICAL REGION FEEDBACK",
    "fitResult.chestName": "Chest & Pectoral",
    "fitResult.chestMetric": "Comfortable ease calibrated to torso",
    "fitResult.chestRating": "Natural",
    "fitResult.waistName": "Waist & Lateral Drape",
    "fitResult.waistMetric": "Tailored contour with ergonomic clearance",
    "fitResult.waistRating": "Slightly Fitted",
    "fitResult.shoulderName": "Shoulder Drop",
    "fitResult.shoulderMetric": "Clean seam alignment with zero bunching",
    "fitResult.shoulderRating": "Aligned",
    "fitResult.fineTune": "Fine-Tune Dimensions",
    "fitResult.composeOutfit": "Compose Full Outfit",
    "colorStudio.title": "Color Studio",
    "colorStudio.subtitle": "Spectral Undertone Analysis",
    "colorStudio.calibration": "SPECTRAL CALIBRATION",
    "colorStudio.primarySkin": "PRIMARY SKIN HARMONY",
    "colorStudio.undertone": "Undertone",
    "colorStudio.contrast": "Contrast",
    "colorStudio.complementaryTitle": "Complementary Palette",
    "colorStudio.complementarySubtitle": "High resonant contrast",
    "colorStudio.neutralTitle": "Essential Neutrals",
    "colorStudio.neutralSubtitle": "Everyday foundational tones",
    "colorStudio.accentTitle": "Subtle Accents",
    "colorStudio.accentSubtitle": "Muted seasonal highlights",
    "colorStudio.viewRecommendations": "View Wardrobe Recommendations",
    "colorStudio.recalibrate": "Recalibrating...",
    "colorStudio.analyzeAgain": "Analyze Face Undertone Again",
    "colorRecommendations.title": "Your Wardrobe Palette",
    "colorRecommendations.subtitle": "Ranked by Color Resonance",
    "colorRecommendations.matchBadge": "Cool Mineral Undertone Match",
    "colorRecommendations.matchDesc": "garments in your wardrobe produce high flattering contrast against your facial skin values.",
    "colorRecommendations.worksWellTitle": "Works Well with Your Palette",
    "colorRecommendations.worksWellSubtitle": "Direct alignment with complementary & neutral spectrums",
    "colorRecommendations.otherTonesTitle": "Other Tones in Wardrobe",
    "colorRecommendations.otherTonesSubtitle": "Neutral foundation or high contrasting pieces",
    "colorRecommendations.tryOn": "Try On",
    "outfitBuilder.title": "Outfit Composition",
    "outfitBuilder.subtitle": "Multi-Layer Silhouetting",
    "outfitBuilder.save": "Save",
    "outfitBuilder.slotTop": "Top",
    "outfitBuilder.slotOuterwear": "Outerwear",
    "outfitBuilder.slotBottom": "Bottom",
    "outfitBuilder.slotShoes": "Shoes",
    "outfitBuilder.selectPiece": "SELECT PIECE FOR",
    "outfitBuilder.emptySlot": "No garments in this category",
    "outfitBuilder.saveLookBtn": "Save Composed Look",
    "savedLook.composed": "Composed",
    "savedLook.fitHarmony": "FIT HARMONY",
    "savedLook.piecesSection": "COMPOSING GARMENTS",
    "savedLook.tryOnOutfit": "Try On this Outfit in 3D",
    "savedLook.editLayers": "Edit Outfit Layers",
    "savedLook.deleteLook": "Delete Look",
    "settings.title": "Settings & Profile",
    "settings.subtitle": "Atelier Preferences",
    "settings.body_measurements": "BODY & MEASUREMENTS",
    "settings.measurements_profile": "Measurements Profile",
    "settings.edit": "Edit",
    "settings.default_fit_cut": "Default Fit Cut",
    "settings.regular_structured": "Regular Structured",
    "settings.nominal": "Nominal",
    "settings.appearance_color": "APPEARANCE & COLOR",
    "settings.personal_color_palette": "Personal Color Palette",
    "settings.wardrobe_inventory": "WARDROBE INVENTORY",
    "settings.archived_garments": "Archived Garments",
    "settings.tops_outerwear_pants_shoes": "Tops, outerwear, pants & shoes",
    "settings.general_preferences": "GENERAL PREFERENCES",
    "settings.atelier_notifications": "Atelier Notifications",
    "settings.seasonal_recommendations": "Seasonal & palette recommendations",
    "settings.measurement_units": "Measurement Units",
    "settings.metric": "Metric (cm / kg)",
    "settings.imperial": "Imperial (in / lbs)",
    "settings.dark_mode": "Dark Mode",
    "settings.language": "Language",
    "settings.english": "English",
    "settings.spanish": "Español",
    "settings.privacy_body_data": "Privacy & Body Data",
    "settings.stored_locally": "Stored locally on device"
  },
  "es": {
    "common.back": "Atrás",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.done": "Listo",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.close": "Cerrar",
    "common.reset": "Restablecer",
    "common.apply": "Aplicar",
    "common.search": "Buscar",
    "common.viewAll": "Ver todos",
    "common.step": "Paso",
    "common.of": "de",
    "common.today": "Hoy",
    "common.all": "Todos",
    "common.tops": "Superiores",
    "common.outerwear": "Abrigos",
    "common.pants": "Pantalones",
    "common.shoes": "Calzado",
    "common.accessories": "Accesorios",
    "app.navTitle": "Navegador de Flujo FitGlass",
    "app.navSubtitle": "Salta directamente a cualquiera de las 16 pantallas nativas",
    "app.allScreens": "Todas las Pantallas (16)",
    "header.brand": "FitGlass",
    "header.subtitle": "Atelier de Guardarropa Digital",
    "tabs.home": "Inicio",
    "tabs.wardrobe": "Armario",
    "tabs.fittingRoom": "Probador",
    "tabs.colorStudio": "Color",
    "tabs.profile": "Perfil",
    "welcome.brandBadge": "ATELIER · OTOÑO / INVIERNO 2026",
    "welcome.wordmark": "FITGLASS",
    "welcome.tagline": "Guardarropa virtual y probador 3D inteligente.",
    "welcome.calibration": "PROPORCIÓN CORPORAL · MATRIZ ÓPTICA 1:1.618",
    "welcome.feature1Title": "Perfil Digital",
    "welcome.feature1Desc": "Simulación milimétrica y precisa del cuerpo",
    "welcome.feature2Title": "Caída y Ajuste",
    "welcome.feature2Desc": "Predicción de tensión y drapeado 3D",
    "welcome.feature3Title": "Estudio de Color",
    "welcome.feature3Desc": "Resonancia armónica de paleta facial",
    "welcome.getStarted": "Comenzar",
    "welcome.haveAccount": "Ya tengo una cuenta",
    "bodyProfile.stepBadge": "PASO 01 DE 02",
    "bodyProfile.title": "Crea tu perfil de ajuste",
    "bodyProfile.subtitle": "Tus medidas permiten a FitGlass simular la caída exacta de la prenda.",
    "bodyProfile.metric": "Métrico (cm)",
    "bodyProfile.imperial": "Imperial (pulg)",
    "bodyProfile.calibrationBadge": "CALIBRACIÓN PARAMÉTRICA",
    "bodyProfile.calibrationDesc": "Avatar milimétrico generado localmente a partir de proporciones biomecánicas.",
    "bodyProfile.height": "Altura",
    "bodyProfile.weight": "Peso",
    "bodyProfile.chest": "Contorno de Pecho",
    "bodyProfile.waist": "Contorno de Cintura",
    "bodyProfile.hips": "Anchura de Cadera",
    "bodyProfile.shoulders": "Ancho de Hombros",
    "bodyProfile.saveProfile": "Guardar Perfil y Continuar",
    "bodyProfile.skip": "Omitir por ahora (usar maniquí estándar)",
    "home.heroPreheader": "OTOÑO / INVIERNO 2026",
    "home.heroTitle": "Tu guardarropa, a tu perfecta medida.",
    "home.heroSubtitle": "Simula caída de tela, tensión y armonía de color en tu silueta digital.",
    "home.fittingRoom": "Probador 3D",
    "home.addClothing": "Añadir Prenda",
    "home.quickAddGarment": "Añadir Prenda",
    "home.quickFittingRoom": "Probador",
    "home.quickColorStudio": "Estudio Color",
    "home.quickAllClothes": "Toda la Ropa",
    "home.recentLooks": "Conjuntos Recientes",
    "home.recentLooksSubtitle": "Atuendos creados y equilibrio de silueta",
    "home.buildOutfit": "Crear Conjunto",
    "home.garmentsCount": "prendas",
    "home.yourWardrobe": "Tu Guardarropa",
    "home.recentGarments": "Prendas analizadas recientemente",
    "home.colorPalette": "Paleta de Color",
    "home.skinUndertone": "Resonancia del subtipo de piel",
    "home.studio": "Estudio",
    "home.neutralHarmonies": "Armonías Neutras y Profundas Seleccionadas",
    "wardrobe.title": "Armario",
    "wardrobe.curatedPieces": "prendas curadas",
    "wardrobe.searchPlaceholder": "Buscar prenda, color, marca...",
    "wardrobe.filterTitle": "Filtrar Armario",
    "wardrobe.filterSubtitle": "Refina por silueta de ajuste o armonía de paleta",
    "wardrobe.filterFit": "Silueta de Ajuste",
    "wardrobe.filterPalette": "Solo Armonía de Paleta",
    "wardrobe.filterPaletteDesc": "Mostrar únicamente prendas afines a tu tono de piel",
    "wardrobe.reset": "Restablecer",
    "wardrobe.apply": "Aplicar Filtros",
    "wardrobe.emptyTitle": "No se encontraron prendas",
    "wardrobe.emptyDesc": "Intenta modificar el término de búsqueda o los filtros activos.",
    "addGarment.title": "Añadir una prenda",
    "addGarment.confirmCapture": "Confirmar captura",
    "addGarment.cameraFrame": "Encuadre de cámara",
    "addGarment.detected": "PRENDA DETECTADA",
    "addGarment.hint": "Coloca la prenda sobre una superficie limpia para mejores resultados.",
    "addGarment.retake": "Repetir Foto",
    "addGarment.analyze": "Analizar Prenda",
    "addGarment.tapShutter": "Presiona el obturador para capturar los bordes",
    "garmentProcessing.badge": "PROCESAMIENTO · VISIÓN COMPUTACIONAL",
    "garmentProcessing.title": "Analizando prenda",
    "garmentProcessing.subtitle": "Extrayendo límites espaciales, atributos del tejido y paleta cromática.",
    "garmentProcessing.step1": "Eliminando fondo",
    "garmentProcessing.step1Desc": "Segmentación de bordes y máscara limpia",
    "garmentProcessing.step2": "Identificando prenda",
    "garmentProcessing.step2Desc": "Detección de categoría y estructura textil",
    "garmentProcessing.step3": "Extrayendo colores",
    "garmentProcessing.step3Desc": "Agrupamiento hexadecimal y etiquetas tonales",
    "garmentProcessing.step4": "Preparando datos 3D",
    "garmentProcessing.step4Desc": "Límites de deformación para simulación",
    "garmentProcessing.complete": "ANÁLISIS COMPLETADO",
    "garmentProcessing.viewExtracted": "Ver Atributos Extraídos",
    "garmentDetails.title": "Atributos de Prenda",
    "garmentDetails.subtitle": "Extraídos por el Motor de Visión",
    "garmentDetails.matteTag": "FONDO ELIMINADO · MÁSCARA LIMPIA",
    "garmentDetails.nameLabel": "NOMBRE DE LA PRENDA",
    "garmentDetails.categoryLabel": "CATEGORÍA",
    "garmentDetails.brandLabel": "MARCA / ATELIER",
    "garmentDetails.materialLabel": "TEJIDO Y COMPOSICIÓN",
    "garmentDetails.colorLabel": "PALETA DE COLOR EXTRAÍDA",
    "garmentDetails.sizeLabel": "ESPECIFICACIÓN DE TALLA",
    "garmentDetails.fitLabel": "CORTE DE AJUSTE",
    "garmentDetails.notesLabel": "NOTAS DE ESTILO",
    "garmentDetails.save": "Guardar en Armario",
    "garmentDetails.cancel": "Cancelar",
    "garmentView.sizeBadge": "TALLA",
    "garmentView.paletteHarmony": "ARMONÍA DE PALETA",
    "garmentView.added": "AÑADIDO",
    "garmentView.tryOn": "Probar en 3D",
    "garmentView.editAttributes": "Editar Atributos",
    "garmentView.fabricDetails": "TEJIDO Y ESPECIFICACIONES",
    "garmentView.material": "Material",
    "garmentView.fitCut": "Corte",
    "garmentView.colorCode": "Color Hex",
    "garmentView.editorialNotes": "NOTAS EDITORIALES",
    "fittingRoom.badge": "PROBADOR VIRTUAL",
    "fittingRoom.studioTitle": "Estudio de Caída Digital",
    "fittingRoom.fitTag": "AJUSTE",
    "fittingRoom.adjustFit": "Ajustar Caída y Tensión",
    "fittingRoom.switchGarment": "Cambiar Prenda",
    "fittingRoom.seeResult": "Ver Resultado de Ajuste",
    "fittingRoom.buildOutfit": "Crear Conjunto",
    "fittingRoom.sheetTitle": "Calibración Paramétrica",
    "fittingRoom.sheetSubtitle": "Ajusta la tensión y drapeado en los puntos clave de tu anatomía",
    "fittingRoom.targetSize": "TALLA OBJETIVO",
    "fittingRoom.tensionEased": "Holgado / Relajado",
    "fittingRoom.tensionSnug": "Ceñido / Entallado",
    "fittingRoom.tensionLabel": "Tensión General de Ajuste",
    "fittingRoom.chestLabel": "Anchura de Pecho",
    "fittingRoom.waistLabel": "Anchura de Cintura",
    "fittingRoom.hipsLabel": "Contorno de Cadera",
    "fittingRoom.shouldersLabel": "Amplitud de Hombros",
    "fittingRoom.applyFit": "Aplicar Calibración",
    "fittingRoom.switchSheetTitle": "Seleccionar Prenda para Probar",
    "fittingRoom.switchSheetSubtitle": "Elige de tu guardarropa digital",
    "fitResult.title": "Análisis de Ajuste",
    "fitResult.scoreBadge": "PUNTUACIÓN DE EVALUACIÓN",
    "fitResult.scoreValue": "Equilibrio Óptimo",
    "fitResult.scorePercent": "98.4% ARMONÍA",
    "fitResult.scoreDesc": "La tensión de la tela en el torso está equilibrada. No se detectan arrugas ni tiranteces excesivas.",
    "fitResult.regionHeader": "EVALUACIÓN POR REGIÓN ANATÓMICA",
    "fitResult.chestName": "Pecho y Pectoral",
    "fitResult.chestMetric": "Holgura cómoda calibrada al torso",
    "fitResult.chestRating": "Natural",
    "fitResult.waistName": "Cintura y Caída Lateral",
    "fitResult.waistMetric": "Contorno entallado con holgura ergonómica",
    "fitResult.waistRating": "Ligeramente Entallado",
    "fitResult.shoulderName": "Caída de Hombro",
    "fitResult.shoulderMetric": "Alineación de costura limpia sin pliegues",
    "fitResult.shoulderRating": "Alineado",
    "fitResult.fineTune": "Ajustar Dimensiones",
    "fitResult.composeOutfit": "Crear Conjunto Completo",
    "colorStudio.title": "Estudio de Color",
    "colorStudio.subtitle": "Análisis Espectral de Subtono",
    "colorStudio.calibration": "CALIBRACIÓN ESPECTRAL",
    "colorStudio.primarySkin": "ARMONÍA PRINCIPAL DE PIEL",
    "colorStudio.undertone": "Subtono",
    "colorStudio.contrast": "Contraste",
    "colorStudio.complementaryTitle": "Paleta Complementaria",
    "colorStudio.complementarySubtitle": "Alto contraste y resonancia",
    "colorStudio.neutralTitle": "Neutros Esenciales",
    "colorStudio.neutralSubtitle": "Tonos base para el día a día",
    "colorStudio.accentTitle": "Acentos Sutiles",
    "colorStudio.accentSubtitle": "Toques de luz estacionales",
    "colorStudio.viewRecommendations": "Ver Recomendaciones del Armario",
    "colorStudio.recalibrate": "Recalibrando...",
    "colorStudio.analyzeAgain": "Analizar Subtono Facial de Nuevo",
    "colorRecommendations.title": "Paleta de tu Armario",
    "colorRecommendations.subtitle": "Ordenado por Resonancia de Color",
    "colorRecommendations.matchBadge": "Coincidencia con Subtono Mineral Frío",
    "colorRecommendations.matchDesc": "prendas de tu armario producen un contraste muy favorecedor con el tono de tu piel.",
    "colorRecommendations.worksWellTitle": "Combina con tu Paleta",
    "colorRecommendations.worksWellSubtitle": "Alineación directa con gamas complementarias y neutras",
    "colorRecommendations.otherTonesTitle": "Otros Tonos en el Armario",
    "colorRecommendations.otherTonesSubtitle": "Base neutra o piezas de alto contraste",
    "colorRecommendations.tryOn": "Probar",
    "outfitBuilder.title": "Composición de Conjuntos",
    "outfitBuilder.subtitle": "Silueteado por Capas",
    "outfitBuilder.save": "Guardar",
    "outfitBuilder.slotTop": "Superior",
    "outfitBuilder.slotOuterwear": "Abrigo",
    "outfitBuilder.slotBottom": "Inferior",
    "outfitBuilder.slotShoes": "Calzado",
    "outfitBuilder.selectPiece": "SELECCIONAR PRENDA PARA",
    "outfitBuilder.emptySlot": "No hay prendas en esta categoría",
    "outfitBuilder.saveLookBtn": "Guardar Conjunto Compuesto",
    "savedLook.composed": "Compuesto",
    "savedLook.fitHarmony": "ARMONÍA DE AJUSTE",
    "savedLook.piecesSection": "PRENDAS DEL CONJUNTO",
    "savedLook.tryOnOutfit": "Probar este Conjunto en 3D",
    "savedLook.editLayers": "Editar Capas del Conjunto",
    "savedLook.deleteLook": "Eliminar Conjunto",
    "settings.title": "Configuración y Perfil",
    "settings.subtitle": "Preferencias del Atelier",
    "settings.body_measurements": "CUERPO Y MEDIDAS",
    "settings.measurements_profile": "Perfil de Medidas",
    "settings.edit": "Editar",
    "settings.default_fit_cut": "Corte de Ajuste Predeterminado",
    "settings.regular_structured": "Estructurado Regular",
    "settings.nominal": "Nominal",
    "settings.appearance_color": "APARIENCIA Y COLOR",
    "settings.personal_color_palette": "Paleta de Color Personal",
    "settings.wardrobe_inventory": "INVENTARIO DEL GUARDARROPA",
    "settings.archived_garments": "Prendas Archivadas",
    "settings.tops_outerwear_pants_shoes": "Prendas superiores, abrigos, pantalones y calzado",
    "settings.general_preferences": "PREFERENCIAS GENERALES",
    "settings.atelier_notifications": "Notificaciones del Atelier",
    "settings.seasonal_recommendations": "Recomendaciones estacionales y paleta",
    "settings.measurement_units": "Unidades de Medida",
    "settings.metric": "Métrico (cm / kg)",
    "settings.imperial": "Imperial (in / lbs)",
    "settings.dark_mode": "Modo Oscuro",
    "settings.language": "Idioma",
    "settings.english": "English",
    "settings.spanish": "Español",
    "settings.privacy_body_data": "Privacidad y Datos Corporales",
    "settings.stored_locally": "Almacenado localmente en el dispositivo"
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'es',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations.en;
    if (dict[key]) return dict[key];
    if (translations.en[key]) return translations.en[key];
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export const useTranslation = () => {
  const { language, setLanguage, toggleLanguage, t } = useLanguage();
  return {
    t,
    i18n: {
      language,
      changeLanguage: (lang: Language) => setLanguage(lang),
    },
    toggleLanguage,
  };
};
